Releasenotes + besproken wijzigingen voor versie 1.3
VNG-Realisatie/Haal-Centraal-BRK-bevragen pull request #772
Opened 2020-12-10 14:29 UTC by JohanBoer

2020-12-10 14:43 UTC, fsamwel commented on docs/releasenotes.md
> ----
waarom wordt dit weggehaald? Dan kan je de releasenotes niet meer goed raadplegen vanuit pages

2020-12-10 15:08 UTC, JohanBoer commented on docs/releasenotes.md
> ----
Heb ik niet bewust gedaan. Ik wist niet dat dit deze functie heeft. Zal het gelijk weer toevoegen.

2020-12-10 15:43 UTC, fsamwel commented
in Stuk is oorspronkelijkStukIdentificatie verwijderd. Maar in StukLinks zit nog wel oorspronkelijkStuk. Ik denk dat deze ook moet worden verwijderd

2020-12-11 08:07 UTC, MelvLee commented on docs/releasenotes.md
> +  - Om het publiceren van onze specificaties met Github.Pages mogelijk te maken zijn diverse documenten verplaatst naar de /docs.
Github.Pages => GitHub Pages. Zie https://pages.github.com/

2020-12-11 08:19 UTC, MelvLee commented on specificatie/hypotheken.yaml
> +        Raadpleeg hypotheken die rusten op een kadastraal onroerende zaak en bijbehorende hypotheekhouder(s). Een hypotheekhouder vestigt als geldverstrekker een recht van hypotheek als zekerheid voo
Elke zin in een eigen regel? Dit gebeurt soms wel en soms niet. Is wel makkelijker bij het lezen. Dan hoeft je niet heen en weer te scrollen

2020-12-11 08:19 UTC, MelvLee commented on specificatie/hypotheken.yaml
> +        Raadpleeg een hypotheek die rust op een kadastraal onroerende zaak en bijbehorende hypotheekhouder(s). Een hypotheekhouder vestigt als geldverstrekker een recht van hypotheek als zekerheid vo
Elke zin in een eigen regel? Dit gebeurt soms wel en soms niet. Is wel makkelijker bij het lezen. Dan hoeft je niet heen en weer te scrollen

2020-12-11 08:19 UTC, MelvLee commented on specificatie/kadaster-natuurlijk-personen.yaml
> +                    Raadpleeg een bij het kadaster geregistreerde natuurlijke persoon die niet in de basisregistratie personen (BRP) is ingeschreven, of wel is ingeschreven maar niet is gekoppeld bij
Elke zin in een eigen regel? Dit gebeurt soms wel en soms niet. Is wel makkelijker bij het lezen. Dan hoeft je niet heen en weer te scrollen

2020-12-11 08:20 UTC, MelvLee commented on specificatie/kadaster-natuurlijk-personen.yaml
> +                    Zoek bij het kadaster geregistreerde natuurlijke personen die niet in de basisregistratie personen (BRP) zijn ingeschreven, of wel zijn ingeschreven maar niet gekoppeld bij het in
Elke zin in een eigen regel? Dit gebeurt soms wel en soms niet. Is wel makkelijker bij het lezen. Dan hoeft je niet heen en weer te scrollen

2020-12-11 08:20 UTC, MelvLee commented on specificatie/kadaster-niet-natuurlijk-personen.yaml
> +                    Raadpleeg een bij het kadaster geregistreerde niet natuurlijke persoon die niet in het Handelsregister (HR) is ingeschreven, of wel is ingeschreven maar niet is gekoppeld bij het
Elke zin in een eigen regel? Dit gebeurt soms wel en soms niet. Is wel makkelijker bij het lezen. Dan hoeft je niet heen en weer te scrollen

2020-12-11 08:20 UTC, MelvLee commented on specificatie/kadaster-niet-natuurlijk-personen.yaml
> +                    Zoek bij het kadaster geregistreerde niet natuurlijke personen die niet in het Handelsregister (HR) zijn ingeschreven, of wel zijn ingeschreven maar niet gekoppeld bij het inschri
Elke zin in een eigen regel? Dit gebeurt soms wel en soms niet. Is wel makkelijker bij het lezen. Dan hoeft je niet heen en weer te scrollen

2020-12-11 08:21 UTC, MelvLee commented on specificatie/zakelijk-gerechtigden.yaml
> +                    Zoek zakelijk gerechtigden van een kadastraal onroerende zaak. Het aandeel van de zakelijk gerechtigde wordt altijd geleverd in combinatie met het gezamenlijk aandeel. Er is een g
Elke zin in een eigen regel? Dit gebeurt soms wel en soms niet. Is wel makkelijker bij het lezen. Dan hoeft je niet heen en weer te scrollen

2020-12-11 15:52 UTC, JohanBoer commented on docs/releasenotes.md
> +  - Om het publiceren van onze specificaties met Github.Pages mogelijk te maken zijn diverse documenten verplaatst naar de /docs.
Aangepast

2020-12-14 09:04 UTC, rhengeveld requested changes
Misschien zie ik iets over het hoofd, maar volgens mij:
* `stukken` zijn _templated_ links (toch?) en hoeven zodoende alleen een _array_ te zijn in het geval van `ZakelijkGerechtigdeLinks`
* `stukdelen` zijn _templated_ links (toch?) en hoeven zodoende _**niet**_ een _array_ te zijn in het geval van `KadastraalOnroerendeZaakLinks`

Als dit voor het gemakt / consistentie wordt gedaan dan kan ik dat begrijpen 🙂 

---

**Stukken**
|Type|Templated met veld|Array nodig?|
|:---|:---|:---|
|KadastraalOnroerendeZaakLinks|stukIdentificaties|N|
|ZakelijkGerechtigdeLinks|stukIdentificaties, tenaamstelling.stukIdentificaties, tenaamstelling.aantekeningen.stukIdentificaties, zakelijkRecht.stukIdentificaties|J|
|HypotheekLinks|stukIdentificaties|N|
|BeslagLinks|stukIdentificaties|N|
|PrivaatrechtelijkeBeperkingLinks|stukIdentificaties|N|
|PubliekrechtelijkeBeperkingLinks|stukIdentificaties|N|

**Stukdelen**
|Type|Templated met veld|Array nodig?|
|:---|:---|:---|
|KadastraalOnroerendeZaakLinks|isVermeldInStukdeelIdentificaties|N|
|ZakelijkGerechtigdeLinks|isGebaseerdOpStukdeelIdentificatie, isVermeldInStukdeelIdentificaties, tenaamstelling.isGebaseerdOpStukdeelIdentificatie, tenaamstelling.isVermeldInStukdeelIdentificaties, tenaamstelling.aantekeningen.isGebaseerdOpStukdeelIdentificatie, tenaamstelling.aantekeningen.isVermeldInStukdeelIdentificaties, zakelijkRecht.isGebaseerdOpStukdeelIdentificatie, zakelijkRecht.isVermeldInStukdeelIdentificaties|J|
|HypotheekLinks|isGebaseerdOpStukdeelIdentificatie, isVermeldInStukdeelIdentificaties|J|
|BeslagLinks|isGebaseerdOpStukdeelIdentificatie, isVermeldInStukdeelIdentificaties|J|
|PrivaatrechtelijkeBeperkingLinks|isGebaseerdOpStukdeelIdentificatie, isVermeldInStukdeelIdentificaties|J|
|PubliekrechtelijkeBeperkingLinks|isGebaseerdOpStukdeelIdentificatie, isVermeldInStukdeelIdentificaties|J|

2020-12-14 09:52 UTC, JohanBoer commented
Door overal een array toe te voegen geven we de provider de keuze om al dan niet templated links te gebruiken.

2020-12-14 09:52 UTC, rhengeveld approved these changes

2020-12-14 09:53 UTC, fsamwel approved these changes

2020-12-14 09:54 UTC, MelvLee approved these changes

2020-12-14 09:54 UTC, merged