Camelcasing toegepast op pathparameter kadastraalOnroerendeZaakIdenti…
VNG-Realisatie/Haal-Centraal-BRK-bevragen pull request #781
Opened 2021-01-20 16:10 UTC by JohanBoer

…ficatie nav #779

2021-01-21 07:21 UTC, MelvLee commented on specificatie/openapi.yaml
>    /kadasternatuurlijkpersonen/{kadasternatuurlijkpersoonidentificatie}:
Moeten deze ook niet aan camelCasing voldoen?

2021-01-21 07:22 UTC, MelvLee commented on specificatie/openapi.yaml
> +  /kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificatie}/hypotheken/{hypotheekidentificatie}:
Moet hypotheekidentificatie niet in camelcase?

2021-01-21 07:23 UTC, MelvLee commented on specificatie/openapi.yaml
> +  /kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificatie}/beslagen/{beslagidentificatie}:
beslagidentificatie in camelcase?

2021-01-21 07:24 UTC, MelvLee commented on specificatie/openapi.yaml
> +  /kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificatie}/privaatrechtelijkebeperkingen/{privaatrechtelijkebeperkingidentificatie}:
privaatrechtelijkebeperkingidentificatie in camelcase?

2021-01-21 07:26 UTC, MelvLee commented on specificatie/openapi.yaml
>    /stukken/{stukidentificatie}:
stukidentificatie in camelcase?

2021-01-21 07:28 UTC, MelvLee commented on specificatie/privaat-rechtelijke-beperkingen.yaml
> +  /kadastraalonroerendezaken/{kadastraalOnroerendeZaakIdentificatie}/privaatrechtelijkebeperkingen/{privaatrechtelijkebeperkingidentificatie}:
privaatrechtelijkebeperkingidentificatie in camelcase?

2021-01-21 07:29 UTC, MelvLee requested changes
Wat ik zie is dat alleen voor kadastraalonroerendezaakidentificatie path parameter camelcasing is toegepast. Volgens mij moet het ook voor de andere path parameters

2021-01-21 14:56 UTC, JohanBoer commented
> Wat ik zie is dat alleen voor kadastraalonroerendezaakidentificatie path parameter camelcasing is toegepast. Volgens mij moet het ook voor de andere path parameters

Thanks Melvin, pak ik op. Had ik zelf moeten bedenken

2021-01-22 08:49 UTC, fsamwel approved these changes

2021-01-22 09:02 UTC, MelvLee approved these changes

2021-01-22 15:41 UTC, merged