Wijzigingen n.a.v. #793
VNG-Realisatie/Haal-Centraal-BRK-bevragen pull request #797
Opened 2021-02-24 15:42 UTC by JohanBoer

Door het hergebruik van AantekeningBasis in zowel hypotheek als beslag heb ik een oplossing bedacht die jullie wel even goed moeten reviewen. Volgens SwaggerHub is deze constructie valide.

2021-02-26 08:51 UTC, MelvLee commented
Voor code generatie in .NET lijkt deze constructie geen probleem te zijn. Waar ik wel moeite mee heb is hoe de hierarchie van de Aantekening schema componenten eruit ziet. Op dit moment ziet het er als volgt uit:

- AantekeningBasis
- AantekeningHypotheek: leidt af van AantekeningBasis
- Aantekening: leidt af van AantekeningHypotheek
- AantekeningTenaamstelling: leidt af van Aantekening

Deze hierarchie is heel verwarrend. Als je naar de namen kijk dan verwacht je niet dat Aantekening van AantekeningHypotheek afleidt. AantekeningHypotheek zou zoals de naam het zegt een specialisatie zijn van Aantekening en niet omgekeerd.
Verder zie ik dat Aantekening eigenlijk een PrivaatrechtelijkeBeperking is of eigenlijk afgeleid door PrivaatrechtelijkeBeperkingHal.
Dit voelt niet goed aan. PrivaatrechtelijkeBeperking is een sub-resource. Er is een path waarmee je een PrivaatrechtelijkeBeperking kan bevragen, maar het bestaat niet als schema component. Misschien is een PrivaatrechtelijkeBeperking gewoon een Aantekening in het informatie model, maar als we het als een sub-resource definieren, dan verwacht ik het ook in het resource model.

Ik denk dat het goed is om de Aantekening hierarchie te herzien.

2021-03-12 11:28 UTC, fsamwel requested changes
@JohanBoer ik ben het eens met @MelvLee over de naamgeving en structuur van aantekeningcomponenten. Pas je die aan? (of wil je hier een overlegde om mogelijkheden te bespreken?)

2021-06-16 12:32 UTC, kad-hebbim commented
De code kan gegenereerd worden, alleen is de hiërarchie inderdaad vrij onduidelijk. 
Is onderstaande manier niet een optie?

**Hierarchie:**
- PrivaatrechtelijkeBeperking extends Aantekening
- AantekeningTenaamstelling extends Aantekening
- Aantekening extends AantekeningBasis
- AantekeningBeslag extends AantekeningBasis
- AantekeningHypotheek extends AantekeningBasis

**Code:**
```
Beslag:
  ...
  aantekeningen:
    type: array
      items:
        $ref: '#/components/schemas/AantekeningBeslag'
Hypotheek:
  ...
  aantekeningen:
    type: array
      items:
        $ref: '#/components/schemas/AantekeningHypotheek'
Tenaamstelling:
  ...
  aantekeningen:
    type: array
      items:
        $ref: '#/components/schemas/AantekeningTenaamstelling'
PrivaatrechtelijkeBeperkingHal:
  allOf:
    - $ref: '#/components/schemas/PrivaatrechtelijkeBeperking'
PrivaatrechtelijkeBeperking:
  allOf:
    - $ref: '#/components/schemas/Aantekening'
AantekeningTenaamstelling:
  allOf:
    - $ref: '#/components/schemas/Aantekening'
    - properties:
        begrenzing:
          deprecated: true
          allOf:
            - $ref: '#/components/schemas/polygonGeoJSON'
        indicatieOorspronkelijkObject:
          type: boolean
          deprecated: true
AantekeningBeslag:
  allOf:
    - $ref: '#/components/schemas/AantekeningBasis'
AantekeningHypotheek:
  allOf:
    - $ref: '#/components/schemas/AantekeningBasis'
    - properties:
        betreftGedeelteVanPerceel:
          type: boolean
          deprecated: false
Aantekening:
  allOf:
    - $ref: '#/components/schemas/AantekeningBasis'
    - properties:
        identificatie:
          type: string
        domein:
          type: string
          description: |
            Het domein waartoe de identificatie behoort.
        einddatum:
          type: string
          format: date
        einddatumRecht:
          type: string
          format: date
        stukIdentificaties:
          type: array
          description: |
            Identificatie van het stuk. Een stuk is een brondocument dat aanleiding geeft
            tot een wijziging van de gegevens in een basisregistratie.
            Dit kan een aangeboden stuk of een kadasterstuk zijn.
          items:
            type: string
        isGebaseerdOpStukdeelIdentificatie:
          type: string
          description: |
            De identificatie van het stukdeel (paragraaf in een akte met een rechtsfeit) waarop deze aantekening is gebaseerd.
        isVermeldInStukdeelIdentificaties:
          type: array
          description: |
            De identificaties van de stukdelen (paragrafen in een akte met een rechtsfeit) waarin deze aantekening is vermeld
          items:
            type: string
AantekeningBasis:
  type: object
  properties:
    aard:
      $ref: '#/components/schemas/Waardelijst'
    omschrijving:
      type: string
    betreftGedeelteVanPerceel:
      type: boolean
      deprecated: true
  description: |
    Waardelijst in deze component :
      [aard](http://www.kadaster.nl/schemas/waardelijsten/AardAantekening/)

2021-06-16 13:18 UTC, JohanBoer commented
@kad-hebbim Deze oplossing is een eleganter, maar dat betekent dat de property "betreftGedeelteVanPerceel" dan niet beschikbaar is in : 
•	PrivaatrechtelijkeBeperking 
•	AantekeningTenaamstelling 
•	Aantekening 

Als dat geen probleem lijkt dit mij een uitstekend voorstel. 

@fsamwel en @MelvLee  Wat vinden jullie hiervan ? 

T.a.v. de opmerking van Melvin over de privaatrechtelijke beperking 

> Misschien is een PrivaatrechtelijkeBeperking gewoon een Aantekening in het informatie model, maar als we het als een sub-resource definieren, dan verwacht ik het ook in het resource model.

Als ik dat doe dan neem ik exact dezelfde structuur 2 keer op. 1 keer als Aantekening en 1 keer als PrivaatrechtelijkeBeperking. 
De response wordt er niet anders van. Wat is dan de reden om dit schemacomponent dubbel op te nemen ? 
Kleine moeite hoor, maar wel dubbele code lijkt mij.

2021-06-17 07:52 UTC, JohanBoer commented
@kad-pothot en @kad-hebbim : Kunnen jullie uitsluitsel geven over de property betreft\gedeelteVanPerceel (zie bovenstaande comments...

2021-06-17 11:22 UTC, fsamwel commented
PrivaatrechtelijkeBeperking is al beschikbaar in productie(v1.2.0) en daarin zit betreftGedeelteVanPerceel. Deze nu niet meer opnemen in PrivaatrechtelijkeBeperking zou een breaking change zijn. Daarom staat in #793 dat dit depricated moet worden, niet dat we deze direct verwijderen.

2021-06-17 11:28 UTC, fsamwel commented
maar als ik de code bekijk van @kad-hebbim dan zit betreftGedeelteVanPerceel in AantekeningBasis.
```
AantekeningBasis:
  type: object
  properties:
    betreftGedeelteVanPerceel:
      type: boolean
      deprecated: true
```

En:
```
Aantekening:
  allOf:
    - $ref: '#/components/schemas/AantekeningBasis'
```

En: 
```
PrivaatrechtelijkeBeperking:
  allOf:
    - $ref: '#/components/schemas/Aantekening'
```

Dus @JohanBoer hoe kan betreftGedeelteVanPerceel niet in PrivaatrechtelijkeBeperking zitten?

2021-06-17 11:28 UTC, fsamwel commented
@kad-hebbim @JohanBoer in de code staat:
```
PrivaatrechtelijkeBeperkingHal:
  allOf:
    - $ref: '#/components/schemas/PrivaatrechtelijkeBeperking'
PrivaatrechtelijkeBeperking:
  allOf:
    - $ref: '#/components/schemas/Aantekening'
```

Hier moet dan nog wel het Hal deel aan worden toegevoegd. Dat is nu alleen niet opgenomen om het korte te houden neem ik aan?

2021-06-21 07:24 UTC, JohanBoer commented
> Dus @JohanBoer hoe kan betreftGedeelteVanPerceel niet in PrivaatrechtelijkeBeperking zitten?

Door mij verkeerd geformuleerd. Is het acceptabel dat in PrivaatrechtelijkeBeperking de property "betreftGedeelteVanPwerceel" deprecated is (Dat was hij in mijn originele voorstel niet.)

2021-06-21 07:25 UTC, JohanBoer commented
> Hier moet dan nog wel het Hal deel aan worden toegevoegd. Dat is nu alleen niet opgenomen om het korte te houden neem ik aan?

Dit voorbeel van @kad-hebbim was in steno om het kort te houden. In de Yamls staan de HAL-componenten er wel netjes bij.

2021-06-21 11:13 UTC, JohanBoer commented
Melvin checked of het voorstel van @kad-hebbim issues oplevert bioj code-genereren.

2021-06-22 12:24 UTC, MelvLee commented
> 
> 
> Melvin checked of het voorstel van @kad-hebbim issues oplevert bioj code-genereren.

deprecated: true in een base class overriden met deprecated: false in een afgeleide levert geen issues op in gegenereerde code

2021-06-22 12:30 UTC, MelvLee commented
Iets anders dat mij is opgevallen door code generatie: AantekeningBeslag introduceren hoeft niet, omdat deze inherit van AantekeningBasis maar geen verdere properties aan toevoegt. Dit wordt weg geoptimaliseerd tijdens code generatie.

2021-06-23 07:18 UTC, JohanBoer commented
> ets anders dat mij is opgevallen door code generatie: AantekeningBeslag introduceren hoeft niet, omdat deze inherit van AantekeningBasis maar geen verdere properties aan toevoegt. Dit wordt weg geoptimaliseerd tijdens code generatie.

Mee eens Melvin, Ik heb ook geen component AantekeningBeslag gemaakt.

2021-06-23 08:54 UTC, JohanBoer commented
Voor deze request hebben we alles gechecked wat we afgesproken hadden. De laatste check was die van Melvin Ik merge deze PR.

2021-06-23 08:54 UTC, merged