Aanpassingen voor versie 1.3
VNG-Realisatie/Haal-Centraal-BRK-bevragen pull request #821
Opened 2021-04-13 18:19 UTC by kad-hebbim

In dit pull request zitten de volgende aanpassingen:

- #799: OnroerendeZaak uitbreiden met filiatie (ontstaanUit) -> testgevallen toegevoegd aan getting started _**_
- #800: OnroerendeZaak(Appartementsrecht) uitbreiden met bijbehorend(e) grondperce(e)l(en) -> openapi.yaml updated
- #815: Testgevallen in getting started is foutief -> kadastraleaanduidingen aangepast in getting started
- #820: OnroerendeZaak uitbreiden met bijbehorende appartementsrechten -> testgevallen toegevoegd aan getting started

_** vervallen percelen werken nog niet; is momenteel onder handen_

2021-04-14 19:27 UTC, JohanBoer requested changes

2021-04-14 19:27 UTC, JohanBoer commented on specificatie/domain.yaml
> +              type: "string"
De items (en dus ookde type: "string" Staan een tab teveel geindenteerd. Beide een tabje minder dus.

2021-04-14 19:27 UTC, JohanBoer commented on specificatie/kadastraal-onroerende-zaken.yaml
> +            items:
Ook hier zijn de items: (en de type: "string") 1 tabje teveel naar rechts gezet.

2021-04-14 19:27 UTC, JohanBoer commented on specificatie/domain.yaml
> +              type: "string"
De items en de type: "string" staan 1 tab teveel naar rechts

2021-04-14 19:30 UTC, JohanBoer commented
Wijzigingen die ik voorstelde zijn al doorgevoerd in de refactor commit.

2021-04-14 19:31 UTC, JohanBoer approved these changes

2021-04-15 07:51 UTC, fsamwel commented on specificatie/domain.yaml
> +                      De kadastraalOnroerendeZaakIdentificaties van de grondpercelen die bij deze Kadastraal Onroerende Zaak (appartementsrecht) hoort
"hoort" = "horen"

2021-04-15 07:57 UTC, fsamwel approved these changes

2021-04-15 08:15 UTC, MelvLee approved these changes

2021-04-15 09:00 UTC, merged