specs: Gorzen en Aanwassen van Gebied
VNG-Realisatie/Haal-Centraal-BRK-bevragen pull request #887
Opened 2021-09-21 12:55 UTC by MelvLee

2021-09-21 16:25 UTC, CathyDingemanse approved these changes

2021-09-22 06:56 UTC, JohanBoer approved these changes

2021-09-22 07:06 UTC, kad-pothot approved these changes

2021-09-22 07:22 UTC, JohanBoer requested changes
Ook deze PR had volgens mij op de Develop gedaan moeten worden. Die is voor 1.3 nog niet gemerged. Volgens mij geen probleem om deze door te voeren op de master omdat het een toevoeging is, maar dan staat dit bestand niet op de develop (kunnen we eventueel ook weer mergen, maar via de develop is de koninklijke weg. Ook geen probleem om deze

2021-09-22 07:46 UTC, MelvLee commented
> 
> 
> Ook deze PR had volgens mij op de Develop gedaan moeten worden. Die is voor 1.3 nog niet gemerged. Volgens mij geen probleem om deze door te voeren op de master omdat het een toevoeging is, maar dan staat dit bestand niet op de develop (kunnen we eventueel ook weer mergen, maar via de develop is de koninklijke weg. Ook geen probleem om deze

Mergen naar develop is geen probleem. Kan via edit worden aangepast. Maar ik zie wel dat we tegen veel merge conflicts gaan lopen om develop te mergen naar master. Ik ga kijken of ik dat recht kan trekken

2021-09-22 10:04 UTC, JohanBoer commented
Wil je deze dan Mergen Melvin ? Er zijn wel voldoende approves. Marcel is op vakantie en Frank heeft het druk met andere zaken.

2021-09-22 10:15 UTC, merged