Wijzigingen n.a.v. live gang versie 1.3
VNG-Realisatie/Haal-Centraal-BRK-bevragen pull request #888
Opened 2021-09-21 15:09 UTC by melsk-r

2021-09-21 16:05 UTC, CathyDingemanse requested changes

2021-09-22 06:55 UTC, JohanBoer approved these changes

2021-09-22 06:56 UTC, melsk-r commented on docs/index.md
>  BRK bevragen bevat nu ook privaatrechtelijke en publiekrechtelijke beperkingen, hypotheken en beslagen!
Done

2021-09-22 07:07 UTC, MelvLee approved these changes

2021-09-22 07:20 UTC, JohanBoer requested changes
Deze wiojzigingen moeten nu toch eerst op de develop aangebracht worden. Die is noig niet gemerged. Dat wil ik vandaag doen. Anders even met deze PR wachten tot de Devlop gemerged is. Even overleg Robert ?

2021-09-22 07:52 UTC, merged