Update index.md
VNG-Realisatie/Haal-Centraal-BRK-bevragen pull request #889
Opened 2021-09-21 16:44 UTC by CathyDingemanse

2021-09-22 06:49 UTC, MelvLee approved these changes

2021-09-22 06:54 UTC, JohanBoer approved these changes

2021-09-22 07:16 UTC, JohanBoer requested changes
Deze toevoegingen heeft Robert al in de Develop Branch gedaan. Die branch ga ik vandaag mergen en dan vervalt de noodzaak voor dit pull request.

2021-11-03 11:53 UTC, CathyDingemanse commented
Deze wijzigingen zijn idd al deels doorgevoerd. Ik zal deze sluiten.

2021-11-03 11:53 UTC, closed without merging